# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miaosha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('maximg', models.CharField(default='', max_length=100)),
                ('hdimg', models.CharField(default='', max_length=100)),
                ('content', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=10)),
                ('miao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
            ],
        ),
    ]
