# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_auto_20181108_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='miaosha',
            name='no',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
