# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-08 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_miaosha_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='miaosha',
            name='sprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='miaosha',
            name='price',
            field=models.IntegerField(),
        ),
    ]
